networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.49.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:2.9.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  grafana:
    image: grafana/grafana:12.0.1
    #platform: linux/arm64  if you use ARM
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - "GF_ALERTING_NOTIFICATION_SKIP_TLS_VERIFY=true"
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # grants admin role to anonymous access
      - GF_AUTH_ANONYMOUS_ENABLED=true # removes login 1/2
      - GF_AUTH_BASIC_ENABLED=false # enable basic auth for API
      # Disable login completely
      # - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      # - "GF_USERS_ALLOW_SIGN_UP=false"
      # Fallback admin credentials
      # - "GF_SECURITY_ADMIN_USER=admin"
      # - "GF_SECURITY_ADMIN_PASSWORD=admin"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  app:
    build: ./app
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana
